version: "2"

services:
    db:
      image: mysql:latest
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: ${PWD}
        MYSQL_DATABASE: ${DB_NAME}
        MYSQL_USER: ${DB_USER}
        MYSQL_PASSWORD: ${PWD}
      volumes:
        - ./db_data:/var/lib/mysql

    tomcat:
      build: .
      environment:
        JDBC_URL: ${URL}
        JDBC_USER: ${DB_USER}
        JDBC_PASS: ${PWD}
#        JPDA_ADDRESS: 8000
#        JPDA_TRANSPORT: dt_socket
        JAVA_TOOL_OPTS: -agentlib:jdwp=transport=dt_socket,server=y,address=8000,suspend=n
#        JAVA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=8000"
      entrypoint: /usr/local/tomcat/bin/catalina.sh jpda run
      ports:
        - 8080:8080
        - 8000:8000
      volumes:
        - ${VOLUMES}
        - ${VOLUMES_MY_SQL}
        - ${VOLUMES_USERS}
        - ${VOLUMES_CONTEXT}
      links:
        - db
      restart: always