db:
  image: mysql:latest
  environment:
    MYSQL_ROOT_PASSWORD: ${PWD}
    MYSQL_DATABASE: ${DB_NAME}
    MYSQL_USER: ${DB_USER}
    MYSQL_PASSWORD: ${PWD}
  #  ports:
  #    - "3306:3306"
  volumes:
    - ./db:/docker-entrypoint-initdb.d

tomcat:
  image: tomcat:latest
  # Environment variables do not appear to be getting loaded the first time Tomcat starts!
  environment:
    JDBC_URL: ${URL}
    JDBC_USER: DB_USER
    JDBC_PASS: PWD
    JPDA_ADDRESS: 8001
    JPDA_TRANSPORT: dt_socket
  ports:
    - "8080:8080"
    - "8001:8001"
  volumes:
    - ${VOLUMES}
  links:
    - db