<footer class="clearfix"><!-- Defining the footer section of the page -->
  <section id="privacy">
    Nicolo&grave; Garbin &copy; 2020 <a class="link" href="https://triboo.com/" rel="noopener noreferrer" target="_blank">The Digital Trasformation Factory</a><br />
    <span>My creation: </span>
    <a class="link" href="https://www.ariston.com/it-it/" rel="noopener noreferrer" target="_blank">Ariston</a>
  </section>
</footer>