version: "3.4"

services:
    db:
      image: mysql:latest
      container_name: db
      restart: always
      ports:
        - "3306:3306"
      environment:
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_DATABASE=${MYSQL_DATABASE}
      volumes:
        - ./db_data:/var/lib/mysql

    tomcat:
      build: .
      container_name: tomcat
      environment:
        JDBC_URL: ${JDBC_URL}
        JDBC_USER: ${JDBC_USER}
        JDBC_PASS: ${JDBC_PASS}
      entrypoint: /usr/local/tomcat/bin/catalina.sh jpda run
      ports:
        - 8080:8080
        - 8000:8000
      volumes:
        - ${VOLUMES}
        - ${VOLUMES_MY_SQL}
        - ${VOLUMES_USERS}
        - ${VOLUMES_CONTEXT}
        - ${VOLUMES_SETENV}
      links:
        - db
      restart: always