version: "3.4"

services:
    db:
      image: mysql:latest
      container_name: db
      restart: always
      ports:
        - "3306:3306"
      environment:
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_DATABASE=${MYSQL_DATABASE}
      volumes:
        - ./db_data:/var/lib/mysql
        - ./init:/docker-entrypoint-initdb.d

    tomcat:
      build: .
      container_name: tomcat
      environment:
        JDBC_URL: ${JDBC_URL}
        JDBC_USER: ${JDBC_USER}
        JDBC_PASS: ${JDBC_PASS}
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
      entrypoint: /usr/local/tomcat/bin/catalina.sh jpda run
      ports:
        - 8080:8080
        - 8000:8000
      volumes:
        - ${WAR}
        - ${VOLUMES_MY_SQL}
        - ${VOLUMES_USERS}
        - ${VOLUMES_CONTEXT}
        - ${VOLUMES_SETENV}
        - ${VOLUMES_GSON}
        - type: bind
          source: ${LOG_FOLDER} # The path to where you want the logs stored on your local machine.
          target: ${LOG_FOLDER_DOCKER} # The path to the logs folder inside the container.
      links:
        - db
      tty: true
      stdin_open: true
      restart: always